# Generated by Django 4.2.2 on 2023-10-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255, verbose_name='فعالیت')),
                ('prediction_progress_start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع پیش بینی شده')),
                ('prediction_progress_end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان پیش بینی شده')),
                ('prediction_progress_start_day', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='تاریخ شروع پیش بینی شده بر اساس روز در سال')),
                ('prediction_progress_end_day', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='تاریخ پایان پیش بینی شده بر اساس روز در سال')),
                ('prediction_progress_days', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='مدت زمان پیشبینی بر اساس روز')),
                ('prediction_progress_start_month', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='تاریخ شروع پیش بینی شده بر اساس ماه در سال')),
                ('prediction_progress_end_month', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='تاریخ پایان پیش بینی شده بر اساس ماه در سال')),
                ('prediction_progress_months', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='مدت زمان پیشبینی بر اساس ماه')),
                ('real_progress_start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع واقعی')),
                ('real_progress_end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان واقعی')),
                ('real_progress_start_day', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='تاریخ شروع واقعی بر اساس روز در سال')),
                ('real_progress_end_day', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='تاریخ پایان واقعی بر اساس روز در سال')),
                ('real_progress_days', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='مدت زمان واقعی بر اساس روز')),
                ('real_progress_start_month', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='تاریخ شروع واقعی بر اساس ماه در سال')),
                ('real_progress_end_month', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='تاریخ پایان واقعی بر اساس ماه در سال')),
                ('real_progress_months', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='مدت زمان واقعی بر اساس ماه')),
                ('activity_completion_percentage', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='درصد پیشرفت فعالیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='task_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_director', to=settings.AUTH_USER_MODEL, verbose_name='مجری')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
