# Generated by Django 5.0 on 2024-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraStoragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت - تومان')),
                ('expiry_days', models.PositiveSmallIntegerField(verbose_name='تعداد روز انقضا پس از فعالسازی')),
                ('storage', models.PositiveSmallIntegerField(help_text='مگابایت', verbose_name='افزایش فضای ذخیره به میزان')),
            ],
            options={
                'verbose_name': 'پلن افزایش حجم',
                'verbose_name_plural': 'پلن های افزایش حجم',
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'لایسنس',
                'verbose_name_plural': 'لایسنس ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VIPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت - تومان')),
                ('tax', models.PositiveIntegerField(default=0, verbose_name='درصد مالیات')),
                ('expiry_days', models.PositiveSmallIntegerField(verbose_name='تعداد روز انقضا پس از فعالسازی')),
                ('max_storage_quote', models.PositiveSmallIntegerField(default=100, verbose_name='حداکثر فضای ذخیره سازی')),
                ('card_background_color', models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze'), ('none', 'none')], default='none', max_length=255, verbose_name='عنوان')),
                ('has_access_to_licence', models.ManyToManyField(blank=True, to='subscription.licence', verbose_name='لایسنس')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن های اشتراک',
                'ordering': ['price'],
            },
        ),
    ]
