# Generated by Django 5.0 on 2024-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_automation_licence_licencesetting_automation_licence_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencesetting',
            name='tax_percent',
            field=models.FloatField(default=0, verbose_name='درصد مالیات شارژ حساب'),
        ),
    ]
