# Generated by Django 5.0 on 2024-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_licencesetting_tax_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencesetting',
            name='automation_licence_is_active',
            field=models.BooleanField(default=True, verbose_name='لایسنس اتوماسیون'),
        ),
        migrations.AddField(
            model_name='licencesetting',
            name='blog_licence_is_active',
            field=models.BooleanField(default=True, verbose_name='لایسنس بلاگ'),
        ),
        migrations.AddField(
            model_name='licencesetting',
            name='financial_licence_is_active',
            field=models.BooleanField(default=True, verbose_name='لایسنس حسابداری'),
        ),
        migrations.AddField(
            model_name='licencesetting',
            name='social_licence_is_active',
            field=models.BooleanField(default=True, verbose_name='لایسنس شبکه های اجتماعی'),
        ),
        migrations.AddField(
            model_name='licencesetting',
            name='warehouse_licence_is_active',
            field=models.BooleanField(default=True, verbose_name='لایسنس انبار داری'),
        ),
    ]
