# Generated by Django 5.0 on 2024-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_licencesetting_automation_licence_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipplan',
            options={'ordering': ['price'], 'verbose_name': 'قیمت اشتراک', 'verbose_name_plural': 'قیمت های اشتراک'},
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='card_background_color',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='expiry_days',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='has_access_to_licence',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='max_storage_quote',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='title',
        ),
        migrations.AlterField(
            model_name='vipplan',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت - تومان'),
        ),
    ]
