# Generated by Django 4.2.2 on 2023-10-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_credit_balance', models.IntegerField(editable=False, help_text='محاسه بر اساس تراکنش های ثبت شده', null=True, verbose_name='مانده حساب - ریال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': '2 - جزئیات مالی حساب',
                'verbose_name_plural': '2 جزئیات مالی حساب ها',
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='آیا تایید شده؟')),
                ('transaction_type', models.CharField(choices=[('برداشت شده از حساب', 'برداشت شده از حساب'), ('واریز شده به حساب', 'واریز شده به حساب')], default='برداشت شده از حساب', max_length=255, verbose_name='نوع تراکنش')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مقدار - ریال')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تراکنش')),
                ('date_of_action', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ اقدام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('attachments', models.ManyToManyField(blank=True, to='gallery.filegallery', verbose_name='ضمیمه ها')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده')),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_accounting.financialaccount', verbose_name='حساب مالی')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': '3 - تراکنش',
                'verbose_name_plural': '3 - تراکنش ها',
                'ordering': ['-date_of_action'],
            },
        ),
        migrations.CreateModel(
            name='FinancialBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=255, verbose_name='نام کارگزار مالی')),
                ('account_owner', models.CharField(max_length=255, verbose_name='نام صاحب حساب')),
                ('account_number', models.CharField(max_length=255, verbose_name='شماره حساب')),
                ('account_ISBN', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا')),
                ('account_card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='financial_broker_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='financial_broker_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': '1 - کارگزار مالی',
                'verbose_name_plural': '1 - کارگزار های مالی',
            },
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='broker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financial_accounting.financialbroker', verbose_name='کارگزار'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='financial_account_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='financial_account_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش کننده'),
        ),
    ]
