# Generated by Django 4.2.6 on 2023-10-31 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='broker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account_broker', to='financial_accounting.financialbroker', verbose_name='کارگزار'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='financial_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record_financial_account', to='financial_accounting.financialaccount', verbose_name='حساب مالی'),
        ),
    ]
