# Generated by Django 4.2.7 on 2023-11-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounting', '0002_alter_financialaccount_broker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialbroker',
            options={'verbose_name': 'کارگزار مالی', 'verbose_name_plural': 'کارگزاران مالی'},
        ),
        migrations.AlterModelOptions(
            name='transactionrecord',
            options={'ordering': ['-date_of_action'], 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='financial_account',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='financialbroker',
            name='calculated_credit_balance',
            field=models.IntegerField(editable=False, help_text='محاسه بر اساس تراکنش های ثبت شده', null=True, verbose_name='مانده حساب - ریال'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='financial_broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record_financial_account', to='financial_accounting.financialbroker', verbose_name='حساب مالی'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FinancialAccount',
        ),
    ]
