# Generated by Django 4.2.7 on 2023-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounting', '0003_alter_financialbroker_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialbroker',
            options={'ordering': ['-updated_by'], 'verbose_name': 'کارگزار مالی', 'verbose_name_plural': 'کارگزاران مالی'},
        ),
        migrations.AlterModelOptions(
            name='transactionrecord',
            options={'ordering': ['-date_of_action', '-updated_at'], 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'برداشت شده از حساب'), ('deposit', 'واریز شده به حساب')], default='برداشت شده از حساب', max_length=255, verbose_name='نوع تراکنش'),
        ),
    ]
