# Generated by Django 4.2.6 on 2023-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filegallery',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='متن جایگزین فایل'),
        ),
        migrations.AlterField(
            model_name='filegallery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file-gallery', verbose_name='فایل'),
        ),
    ]
