# Generated by Django 4.2.6 on 2023-11-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_filegallery_alt_alter_filegallery_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filegallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل', 'verbose_name_plural': 'فایل ها'},
        ),
    ]
