# Generated by Django 4.2.2 on 2023-10-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultural_property_type', models.CharField(choices=[('کتاب', 'کتاب'), ('مجله', 'مجله'), ('بنر', 'بنر'), ('یادبود', 'یادبود'), ('سایر', 'سایر')], max_length=255, verbose_name='نوع کالا')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('number_of_inventory', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد موجودی فعلی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_property_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('images', models.ManyToManyField(blank=True, to='gallery.filegallery', verbose_name='فیلم و تصویر از کالا')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_property_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='آخرین اصلاح توسط')),
            ],
            options={
                'verbose_name': '3 - کالای فرهنگی',
                'verbose_name_plural': '3 - کالا های فرهنگی',
            },
        ),
        migrations.CreateModel(
            name='HouseProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('buying_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت خرید')),
                ('condition', models.CharField(blank=True, choices=[('آکبند', 'آکبند'), ('در حد نو', 'در حد نو'), ('کار کرده با وضعیت خوب', 'کار کرده با وضعیت خوب'), ('کار کرده با وضعیت بد', 'کار کرده با وضعیت بد'), ('خراب', 'خراب')], default='آکبند', max_length=255, verbose_name='شرایط عمومی کالا')),
                ('registration_code', models.CharField(help_text='در صورت تغییر کد مشخصات کاربر تغییر دهنده ذخیره می گردد', max_length=255, verbose_name='کد ثبت کالا')),
                ('date_of_assignment', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('date_of_return', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('house_property_type', models.CharField(choices=[('لوازم خانگی', 'لوازم خانگی'), ('لوازم اداری', 'لوازم اداری')], max_length=255, verbose_name='نوع کالا')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_property_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('images', models.ManyToManyField(blank=True, to='gallery.filegallery', verbose_name='فیلم و تصویر از کالا')),
                ('property_assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_employee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='کالا تحویل شده به')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_property_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='آخرین اصلاح توسط')),
            ],
            options={
                'verbose_name': '2 - کالای خانگی',
                'verbose_name_plural': '2 - کالا های خانگی',
            },
        ),
        migrations.CreateModel(
            name='DigitalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('buying_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت خرید')),
                ('condition', models.CharField(blank=True, choices=[('آکبند', 'آکبند'), ('در حد نو', 'در حد نو'), ('کار کرده با وضعیت خوب', 'کار کرده با وضعیت خوب'), ('کار کرده با وضعیت بد', 'کار کرده با وضعیت بد'), ('خراب', 'خراب')], default='آکبند', max_length=255, verbose_name='شرایط عمومی کالا')),
                ('registration_code', models.CharField(help_text='در صورت تغییر کد مشخصات کاربر تغییر دهنده ذخیره می گردد', max_length=255, verbose_name='کد ثبت کالا')),
                ('date_of_assignment', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('date_of_return', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('digital_property_type', models.CharField(choices=[('رم', 'رم'), ('مادر بورد', 'مادر بورد'), ('کیس', 'کیس'), ('پاور', 'پاور'), ('سی دی', 'سی دی'), ('هارد', 'هارد'), ('سی پی یو', 'سی پی یو'), ('مانیتور', 'مانیتور'), ('کارت گرافیک', 'کارت گرافیک'), ('سایر', 'سایر')], max_length=255, verbose_name='نوع کالا')),
                ('serial_code_1', models.CharField(max_length=255, verbose_name='سریال')),
                ('serial_code_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='سریال دوم در صورت وجود')),
                ('warranty_company', models.CharField(blank=True, default='بدون گارانتی', max_length=255, verbose_name='نام شرکت گارانتی کننده')),
                ('warranty_expiration_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای گارانتی')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_property_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('images', models.ManyToManyField(blank=True, to='gallery.filegallery', verbose_name='فیلم و تصویر از کالا')),
                ('property_assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_employee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='کالا تحویل شده به')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_property_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='آخرین اصلاح توسط')),
            ],
            options={
                'verbose_name': '1 - کالای دیجیتال',
                'verbose_name_plural': '1 - کالا های دیجیتال',
            },
        ),
        migrations.CreateModel(
            name='CulturalPropertyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assign', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ تحویل')),
                ('number_of_assigned_property', models.PositiveIntegerField(verbose_name='تعداد تحویل شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_property_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('cultural_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.culturalproperty', verbose_name='کالای فرهنگی')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='تحویل شده به')),
            ],
            options={
                'verbose_name': '3.2 - تحویل کالای فرهنگی',
                'verbose_name_plural': '3.2 - تحویل کالای فرهنگی',
            },
        ),
        migrations.CreateModel(
            name='CulturalPropertyAddUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_up_number', models.PositiveIntegerField(verbose_name='تعداد اضافه شده')),
                ('date_of_addup', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ افزودن')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_property_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('cultural_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.culturalproperty', verbose_name='کالای فرهنگی')),
            ],
            options={
                'verbose_name': '3.2 - افزودن کالای فرهنگی',
                'verbose_name_plural': '3.2 - افزودن کالای فرهنگی',
            },
        ),
    ]
