# Generated by Django 5.0 on 2024-02-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_user_financial_default_broker_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproperty',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='محل قرار گیری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseproperty',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='محل قرار گیری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='digitalproperty',
            name='property_assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='کالا تحویل شده به'),
        ),
        migrations.AlterField(
            model_name='houseproperty',
            name='property_assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='کالا تحویل شده به'),
        ),
    ]
