# Generated by Django 4.2.6 on 2023-10-31 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metapost',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_robots.bot', verbose_name='auto robot'),
        ),
    ]
