# Generated by Django 4.2.6 on 2023-11-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0002_alter_metapost_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['-created_at'], 'verbose_name': 'ربات', 'verbose_name_plural': 'ربات ها'},
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن ربات'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_token_belongs_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن ربات متعلق به کیست؟'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='has_access_to_channels',
            field=models.CharField(blank=True, help_text='ادرس شبکه بدون @ جداسازی با ,', max_length=3000, null=True, verbose_name='شبکه هایی که دسترسی دارد'),
        ),
    ]
