# Generated by Django 4.2.6 on 2023-11-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0003_alter_bot_options_alter_bot_bot_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapost',
            name='publish_with_bots',
        ),
        migrations.AlterField(
            model_name='metapost',
            name='message_action',
            field=models.CharField(blank=True, choices=[('-', '-'), ('delete', 'حذف'), ('revise', 'ویرایش'), ('republish', 'انتشار مجدد')], max_length=255, null=True, verbose_name='message action'),
        ),
        migrations.AlterField(
            model_name='metapost',
            name='message_status',
            field=models.CharField(blank=True, choices=[('sent', 'منتشر شده'), ('deleted', 'حذف شده'), ('republished', 'مجدد منتشر شده'), ('revised', 'مجدد ویرایش شده'), ('queued', 'زمان بندی شده')], editable=False, max_length=255, null=True, verbose_name='message status'),
        ),
        migrations.AlterField(
            model_name='telegrambothistory',
            name='message_action',
            field=models.CharField(blank=True, choices=[('-', '-'), ('delete', 'حذف'), ('revise', 'ویرایش'), ('republish', 'انتشار مجدد')], max_length=255, null=True, verbose_name='message action'),
        ),
        migrations.AlterField(
            model_name='telegrambothistory',
            name='message_status',
            field=models.CharField(blank=True, choices=[('sent', 'منتشر شده'), ('deleted', 'حذف شده'), ('republished', 'مجدد منتشر شده'), ('revised', 'مجدد ویرایش شده'), ('queued', 'زمان بندی شده')], max_length=255, null=True, verbose_name='message status'),
        ),
    ]
