# Generated by Django 4.2.6 on 2023-11-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0004_remove_metapost_publish_with_bots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metapost',
            old_name='post_view_type',
            new_name='metapost_view_type',
        ),
    ]
