# Generated by Django 4.2.6 on 2023-11-01 14:04

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0005_rename_post_view_type_metapost_metapost_view_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metapost',
            name='categories',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='دسته ها'),
        ),
        migrations.AlterField(
            model_name='metapost',
            name='date_of_action',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ اجرا'),
        ),
        migrations.AlterField(
            model_name='metapost',
            name='keywords',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='metapost',
            name='metapost_view_type',
            field=models.CharField(choices=[('simple_text', 'متن ساده'), ('photo', 'عکس + کپشن'), ('video', 'ویدئو + کپشن'), ('audio', 'صوت + کپشن'), ('document', 'فایل + کپشن')], default='simple_text', max_length=255, verbose_name='نحوه ارسال متا'),
        ),
        migrations.AlterField(
            model_name='metapost',
            name='sub_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='زیر عنوان'),
        ),
        migrations.AlterField(
            model_name='metapost',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='عنوان'),
        ),
    ]
