# Generated by Django 4.2.6 on 2023-11-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0006_alter_metapost_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapost',
            name='message_action',
        ),
    ]
