# Generated by Django 4.2.6 on 2023-11-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0008_balebothistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapost',
            name='action',
            field=models.CharField(choices=[('nothing', 'بدون اقدام'), ('send', 'ارسال'), ('delete', 'حذف'), ('revise', 'ویرایش'), ('republish', 'انتشار مجدد')], default=1, max_length=255, verbose_name='عملیات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metapost',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_robots.bot', verbose_name='ربات'),
        ),
        migrations.AlterField(
            model_name='metapost',
            name='message_status',
            field=models.CharField(blank=True, choices=[('sent', 'منتشر شده'), ('deleted', 'حذف شده'), ('republished', 'مجدد منتشر شده'), ('revised', 'مجدد ویرایش شده'), ('queued', 'زمان بندی شده')], editable=False, max_length=255, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='telegrambothistory',
            name='message_action',
            field=models.CharField(blank=True, choices=[('d', 'c'), ('d', 'c')], max_length=255, null=True, verbose_name='message action'),
        ),
    ]
