# Generated by Django 4.2.6 on 2023-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0009_metapost_action_alter_metapost_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metapost',
            name='action',
            field=models.CharField(choices=[('nothing', 'بدون اقدام'), ('send', 'ارسال'), ('add_to_queue', 'زمانبندی'), ('delete', 'حذف'), ('revise', 'ویرایش'), ('republish', 'انتشار مجدد')], max_length=255, verbose_name='عملیات'),
        ),
    ]
