# Generated by Django 4.2.6 on 2023-11-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0010_alter_metapost_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='balebothistory',
            name='response_message',
            field=models.TextField(default=1, verbose_name='پیام بازگشتی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metapost',
            name='message_status',
            field=models.CharField(blank=True, choices=[('sent', 'منتشر شده'), ('deleted', 'حذف شده'), ('republished', 'مجدد منتشر شده'), ('revised', 'مجدد ویرایش شده'), ('queued', 'زمان بندی شده'), ('failed', 'انتشار ناموفق')], editable=False, max_length=255, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='telegrambothistory',
            name='message_status',
            field=models.CharField(blank=True, choices=[('sent', 'منتشر شده'), ('deleted', 'حذف شده'), ('republished', 'مجدد منتشر شده'), ('revised', 'مجدد ویرایش شده'), ('queued', 'زمان بندی شده'), ('failed', 'انتشار ناموفق')], max_length=255, null=True, verbose_name='message status'),
        ),
    ]
