# Generated by Django 4.2.6 on 2023-11-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0011_balebothistory_response_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eitaabothistory',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='eitaabothistory',
            name='text',
        ),
        migrations.RemoveField(
            model_name='eitaabothistory',
            name='title',
        ),
        migrations.AddField(
            model_name='eitaabothistory',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='message id'),
        ),
        migrations.AddField(
            model_name='eitaabothistory',
            name='response_message',
            field=models.TextField(default=1, verbose_name='پیام بازگشتی'),
            preserve_default=False,
        ),
    ]
