# Generated by Django 4.2.6 on 2023-11-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0012_remove_eitaabothistory_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapost',
            name='message_id',
            field=models.CharField(default=0, editable=False, max_length=255, verbose_name='message id'),
        ),
    ]
