# Generated by Django 4.2.6 on 2023-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0013_metapost_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambothistory',
            name='message_action',
        ),
        migrations.RemoveField(
            model_name='telegrambothistory',
            name='message_status',
        ),
        migrations.RemoveField(
            model_name='telegrambothistory',
            name='method_url',
        ),
        migrations.RemoveField(
            model_name='telegrambothistory',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='telegrambothistory',
            name='response_json',
        ),
        migrations.AddField(
            model_name='telegrambothistory',
            name='media_url',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='media url'),
        ),
        migrations.AddField(
            model_name='telegrambothistory',
            name='response_message',
            field=models.TextField(default=1, verbose_name='پیام بازگشتی'),
            preserve_default=False,
        ),
    ]
