# Generated by Django 4.2.7 on 2023-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0014_remove_telegrambothistory_message_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapost',
            name='attached_file',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='attached_image',
        ),
        migrations.AddField(
            model_name='metapost',
            name='attached_file_link',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='لینک فایل ضمیمه'),
        ),
    ]
