# Generated by Django 4.2.7 on 2023-11-21 21:36

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0015_remove_metapost_attached_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapost',
            name='date_of_action',
        ),
        migrations.AddField(
            model_name='metapost',
            name='send_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='ارسال یک باره'),
        ),
        migrations.AddField(
            model_name='metapost',
            name='send_daily_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='ارسال روزانه'),
        ),
        migrations.AddField(
            model_name='metapost',
            name='send_hourly_at',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='ارسال ساعتی'),
        ),
        migrations.AddField(
            model_name='metapost',
            name='send_monthly_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='ارسال ماهانه'),
        ),
        migrations.AddField(
            model_name='metapost',
            name='send_yearly_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='ارسال سالانه'),
        ),
    ]
