# Generated by Django 4.2.7 on 2023-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0016_remove_metapost_date_of_action_metapost_send_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapost',
            name='is_send_daily_at_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن ارسال روزانه'),
        ),
        migrations.AddField(
            model_name='metapost',
            name='is_send_hourly_at_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن ارسال ساعتی'),
        ),
        migrations.AddField(
            model_name='metapost',
            name='is_send_monthly_at_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن ارسال ماهانه'),
        ),
        migrations.AddField(
            model_name='metapost',
            name='is_send_yearly_at_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن ارسال سالانه'),
        ),
    ]
