# Generated by Django 4.2.7 on 2023-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0017_metapost_is_send_daily_at_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metapost',
            name='action',
            field=models.CharField(choices=[('new_send', 'ارسال جدید'), ('republish', 'انتشار مجدد'), ('revise', 'ویرایش'), ('delete', 'حذف')], max_length=255, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='metapost',
            name='message_status',
            field=models.CharField(blank=True, choices=[('processing', 'در دست اقدام'), ('sent', 'منتشر شده'), ('queued', 'زمانبندی شده'), ('republished', 'مجدد منتشر شده'), ('revised', 'مجدد ویرایش شده'), ('deleted', 'حذف شده'), ('failed', 'انتشار ناموفق')], max_length=255, null=True, verbose_name='وضعیت'),
        ),
    ]
