# Generated by Django 5.0 on 2024-02-06 16:01

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0018_alter_metapost_action_alter_metapost_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapost',
            name='is_send_daily_at_active',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='is_send_hourly_at_active',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='is_send_monthly_at_active',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='is_send_yearly_at_active',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='send_at',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='send_daily_at',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='send_hourly_at',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='send_monthly_at',
        ),
        migrations.RemoveField(
            model_name='metapost',
            name='send_yearly_at',
        ),
        migrations.AddField(
            model_name='metapost',
            name='send_at_date_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ارسال'),
        ),
        migrations.AddField(
            model_name='metapost',
            name='send_at_type',
            field=models.CharField(choices=[('درلحظه یکباره', 'درلحظه یکباره'), ('زمانبندی شده یکباره', 'زمانبندی شده یکباره'), ('روزانه', 'روزانه'), ('هفتگی', 'هفتگی'), ('ماهانه', 'ماهانه'), ('سالانه', 'سالانه')], default=1, max_length=255, verbose_name='نوع ارسال متاپست'),
            preserve_default=False,
        ),
    ]
