# Generated by Django 5.0 on 2024-02-08 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0019_remove_metapost_is_send_daily_at_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eitaabothistory',
            name='metapost',
        ),
        migrations.RemoveField(
            model_name='telegrambothistory',
            name='metapost',
        ),
        migrations.CreateModel(
            name='MetapostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_message', models.TextField(verbose_name='پیام بازگشتی')),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='chat id')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='message id')),
                ('metapost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_robots.metapost', verbose_name='metapost')),
            ],
            options={
                'verbose_name': 'تاریخچه ربات ایتا',
                'verbose_name_plural': 'تاریخچه ربات های ایتا',
            },
        ),
        migrations.DeleteModel(
            name='BaleBotHistory',
        ),
        migrations.DeleteModel(
            name='EitaaBotHistory',
        ),
        migrations.DeleteModel(
            name='TelegramBotHistory',
        ),
    ]
