# Generated by Django 5.0 on 2024-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_robots', '0020_remove_eitaabothistory_metapost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaposthistory',
            options={'verbose_name': 'تاریخچه ارسال متا', 'verbose_name_plural': 'تاریخچه ارسال متا ها'},
        ),
        migrations.AlterField(
            model_name='metapost',
            name='send_at_type',
            field=models.CharField(choices=[('در لحظه یکباره', 'در لحظه یکباره'), ('زمانبندی شده یکباره', 'زمانبندی شده یکباره'), ('روزانه', 'روزانه'), ('هفتگی', 'هفتگی'), ('ماهانه', 'ماهانه'), ('سالانه', 'سالانه')], max_length=255, verbose_name='نوع ارسال متاپست'),
        ),
    ]
