# Generated by Django 4.2.7 on 2023-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='profile',
            name='landline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره ثابت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره همراه'),
        ),
    ]
