# Generated by Django 4.2.7 on 2023-11-22 19:14

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_biography_profile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(editable=False, max_length=255, verbose_name='شماره موبایل')),
                ('pass_code', models.CharField(editable=False, max_length=255, verbose_name='کد احراز')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تایید پیامکی',
                'verbose_name_plural': 'کد های تایید پیامکی',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CheckSmsValidity',
        ),
    ]
