# Generated by Django 4.2.7 on 2023-11-27 09:42

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_smsauthcode_delete_checksmsvalidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraStoragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت - ریال')),
                ('expiry_days', models.PositiveSmallIntegerField(verbose_name='تعداد روز انقضا پس از فعالسازی')),
                ('storage', models.PositiveSmallIntegerField(help_text='مگابایت', verbose_name='افزایش فضای ذخیره به میزان')),
            ],
            options={
                'verbose_name': 'پلن افزایش حجم',
                'verbose_name_plural': 'پلن های افزایش حجم',
            },
        ),
        migrations.CreateModel(
            name='VIPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت - ریال')),
                ('expiry_days', models.PositiveSmallIntegerField(verbose_name='تعداد روز انقضا پس از فعالسازی')),
                ('maximum_storage_quota', models.PositiveSmallIntegerField(default=500, help_text='مگابایت', verbose_name='حداکثر فضای ذخیره سازی')),
                ('metapost_daily_send_limit', models.PositiveSmallIntegerField(verbose_name='تعداد محدودیت روزانه ارسال پیام')),
                ('financial_broker_limit', models.PositiveSmallIntegerField(verbose_name='تعداد محدودیت ساخت کارگزار مالی')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن های اشتراک',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='maximum_storage_quota',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_financial_broker_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='حداکثر تعداد کارگزاران مالی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_maximum_storage_quota',
            field=models.PositiveIntegerField(default=100, help_text='مگابایت', verbose_name='حداکثر فضای ذخیره سازی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_metapost_daily_send_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='حداکثر تعداد پیام ارسالی روزانه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_storage_expiry_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای حجم اضافه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='metapost_daily_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد متاپست ارسالی اخرین روز'),
        ),
        migrations.AddField(
            model_name='profile',
            name='metapost_last_send_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین ارسال متاپست'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vip_plan_expiry_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای اشتراک ویژه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_storage_profile', to='accounts.extrastorageplan', verbose_name='اشتراک'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vip_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vip_plan_profile', to='accounts.vipplan', verbose_name='اشتراک'),
        ),
    ]
