# Generated by Django 4.2.7 on 2023-11-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extrastorageplan_vipplan_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_blog_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_employee',
        ),
    ]
