# Generated by Django 4.2.7 on 2023-11-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_is_blog_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra_storage_expiry_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vip_plan_expiry_date',
        ),
    ]
