# Generated by Django 4.2.7 on 2023-11-27 10:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_extra_storage_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_storage_expiry_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای حجم اضافه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vip_plan_expiry_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای اشتراک ویژه'),
        ),
    ]
