# Generated by Django 4.2.7 on 2023-11-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_extra_storage_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipplan',
            options={'ordering': ['price'], 'verbose_name': 'پلن اشتراک', 'verbose_name_plural': 'پلن های اشتراک'},
        ),
        migrations.AddField(
            model_name='vipplan',
            name='all_licence_activate',
            field=models.BooleanField(default=False, verbose_name='لایسنس تمامی خدمات'),
        ),
        migrations.AddField(
            model_name='vipplan',
            name='full_support',
            field=models.BooleanField(default=False, verbose_name='پشتیبانی کامل'),
        ),
        migrations.AddField(
            model_name='vipplan',
            name='numbers_of_assistant',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد کامندان'),
        ),
    ]
