# Generated by Django 5.0 on 2023-12-31 14:21

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_vipplan_card_background_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra_storage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_financial_broker_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_maximum_storage_quota',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_metapost_daily_send_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_storage_expiry_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='metapost_last_send_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='card_background_color',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ایالت'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='اعتبار کیف پول'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='vipplan',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت - تومان'),
        ),
        migrations.DeleteModel(
            name='ExtraStoragePlan',
        ),
    ]
