# Generated by Django 5.0 on 2024-02-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_extrastorageplan_remove_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_financial_default_broker',
            field=models.TextField(blank=True, null=True, verbose_name='صندوق  مالی پیشفرض'),
        ),
    ]
