# Generated by Django 5.0 on 2024-02-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_user_financial_default_broker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'لایسنس',
                'verbose_name_plural': 'لایسنس ها',
            },
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='all_licence_activate',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='card_background_color',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='financial_broker_limit',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='full_support',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='maximum_storage_quota',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='metapost_daily_send_limit',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='numbers_of_assistant',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile-pic/', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='vipplan',
            name='has_access_to_licence',
            field=models.ManyToManyField(blank=True, to='accounts.licence', verbose_name='لایسنس'),
        ),
    ]
