# Generated by Django 5.0 on 2024-02-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_vipplan_card_background_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licence',
            options={'ordering': ['order'], 'verbose_name': 'لایسنس', 'verbose_name_plural': 'لایسنس ها'},
        ),
        migrations.AddField(
            model_name='licence',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
