# Generated by Django 5.0 on 2024-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_licence_options_licence_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='max_storage_quote',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='حداکثر فضای ذخیره سازی'),
        ),
    ]
