# Generated by Django 5.0 on 2024-02-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_licence_max_storage_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='demo_used_once',
            field=models.BooleanField(default=False, verbose_name='استفاده از دمو'),
        ),
    ]
