# Generated by Django 5.0 on 2024-02-19 16:07

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_demo_used_once'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='storage_plan_expiry_days',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='storage_plan_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='storage_plan_storage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='storage_plan_title',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vip_plan_expiry_days',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vip_plan_financial_broker_limit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vip_plan_maximum_storage_quota',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vip_plan_metapost_daily_send_limit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vip_plan_numbers_of_assistant',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vip_plan_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vip_plan_title',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='مبلغ - تومان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('پرداخت نشده', 'پرداخت نشده'), ('پرداخت شده', 'پرداخت شده')], default='pending', max_length=255, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vip_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vipplan', verbose_name='پلن اشتراک'),
        ),
        migrations.AddField(
            model_name='vipplan',
            name='tax',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد مالیات'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
