# Generated by Django 5.0 on 2024-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_invoice_vip_plan_invoice_invoice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra_storage',
        ),
        migrations.RemoveField(
            model_name='vipplan',
            name='has_access_to_licence',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vip_plan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_financial_broker_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_maximum_storage_quota',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_metapost_daily_send_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='demo_used_once',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_storage_expiry_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vip_plan_expiry_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='automation_licence',
            field=models.BooleanField(default=False, verbose_name='لایسنس اتوماسیون'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blog_licence',
            field=models.BooleanField(default=False, verbose_name='لایسنس بلاگ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='financial_licence',
            field=models.BooleanField(default=False, verbose_name='لایسنس حسابداری'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_licence',
            field=models.BooleanField(default=False, verbose_name='لایسنس شبکه های اجتماعی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='warehouse_licence',
            field=models.BooleanField(default=False, verbose_name='لایسنس انبار داری'),
        ),
        migrations.DeleteModel(
            name='ExtraStoragePlan',
        ),
        migrations.DeleteModel(
            name='Licence',
        ),
        migrations.DeleteModel(
            name='VIPPlan',
        ),
    ]
