# Generated by Django 5.0 on 2024-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_profile_extra_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.PositiveIntegerField(default=1, verbose_name='مالیات - تومان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('پرداخت نشده', 'پرداخت نشده'), ('پرداخت شده', 'پرداخت شده')], default='پرداخت نشده', max_length=255, verbose_name='وضعیت'),
        ),
    ]
