# Generated by Django 5.0 on 2024-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_invoice_tax_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.PositiveIntegerField(default=0, verbose_name='مالیات - تومان'),
        ),
    ]
