# Generated by Django 5.0 on 2024-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_invoice_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_maximum_storage_quota',
            field=models.PositiveIntegerField(default=100, help_text='مگابایت', verbose_name='حداکثر فضای ذخیره سازی'),
        ),
    ]
