# Generated by Django 5.0 on 2024-06-16 12:44

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_profile_default_maximum_storage_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen_by_user', models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': 'اطلاعیه کاربر',
                'verbose_name_plural': 'اطلاعیه های کاربران',
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'صورت حساب', 'verbose_name_plural': 'صورت حساب ها'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('واریز به حساب', 'واریز به حساب'), ('برداشت از حساب', 'برداشت از حساب')], default='واریز به حساب', max_length=255, verbose_name='نوع صورت حساب'),
        ),
    ]
