# Generated by Django 5.0 on 2024-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_usernotification_notification_usernotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آیدی تلگرام کاربر'),
        ),
    ]
