# Generated by Django 4.2.2 on 2023-10-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='ایمیل')),
                ('mobile_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره موبایل')),
                ('landline', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره ثابت')),
                ('generated_url', models.CharField(editable=False, max_length=255, verbose_name='دامنه سیستمی')),
                ('custom_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='دامنه شخصی')),
                ('theme', models.CharField(choices=[('1', 'پوسته 1'), ('2', 'پوسته 2')], default='پوسته 1', max_length=255, verbose_name='پوسته')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug_title', models.CharField(editable=False, max_length=255, verbose_name='اسلاگ عنوان')),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='blogpost/images/', verbose_name='تصویر شاخص')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات مختصر')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='محتوا')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='بلاگ')),
            ],
            options={
                'verbose_name': 'بلاگ پست',
                'verbose_name_plural': 'بلاگ پست ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeaderMenuChildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('href', models.CharField(max_length=255, verbose_name='لینک')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='بلاگ')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'ایتم زیر منو',
                'verbose_name_plural': 'ایتم های زیر منو',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='بلاگ')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('images', models.ManyToManyField(to='gallery.filegallery', verbose_name='تصاویر')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر هدر',
                'verbose_name_plural': 'تصاویر اسلایدر هدر',
            },
        ),
        migrations.CreateModel(
            name='MagicWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug_title', models.CharField(editable=False, max_length=255, verbose_name='اسلاگ عنوان')),
                ('word_type', models.CharField(choices=[('category', 'دسته'), ('keyword', 'کلمه کلیدی')], max_length=255, verbose_name='نوع کلمه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='بلاگ')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'کلمه جادویی',
                'verbose_name_plural': 'کلمات جادویی',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenuParentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('href', models.CharField(max_length=255, verbose_name='لینک')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='بلاگ')),
                ('child', models.ManyToManyField(blank=True, to='blog.headermenuchilditem', verbose_name='زیر آیتم ها')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'ایتم منو',
                'verbose_name_plural': 'ایتم های منو',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='بلاگ')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('menu_items', models.ManyToManyField(to='blog.headermenuparentitem', verbose_name='آیتم های منو')),
            ],
            options={
                'verbose_name': 'منو هدر',
                'verbose_name_plural': 'منو های هدر',
            },
        ),
        migrations.CreateModel(
            name='FeaturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='بلاگ پست')),
            ],
            options={
                'verbose_name': 'پست ویژه',
                'verbose_name_plural': 'پست های ویژه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostUserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_host_name', models.CharField(editable=False, max_length=255, verbose_name='user host name')),
                ('user_ip_address', models.CharField(editable=False, max_length=255, verbose_name='user ip address')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog_post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='بلاگ پست')),
            ],
            options={
                'verbose_name': 'مشاهده بلاگ پست توسط کاربر',
                'verbose_name_plural': 'مشاهده بلاگ پست ها توسط کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('publish_on_site', models.BooleanField(default=False, verbose_name='نمایش نظر در سایت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='بلاگ پست')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نظر گذارنده')),
            ],
            options={
                'verbose_name': 'نظر بلاگ پست',
                'verbose_name_plural': 'نظر های بلاگ پست ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='دفعات مشاهده')),
                ('blog_post', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='بلاگ پست')),
            ],
            options={
                'verbose_name': 'ویژگی بلاگ پست',
                'verbose_name_plural': 'ویژگی های بلاگ پست ها',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'word_type': 'category'}, related_name='blog_post_magic_word_categories', to='blog.magicword', verbose_name='دسته ها'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.ManyToManyField(blank=True, limit_choices_to={'word_type': 'keyword'}, related_name='blog_post_magic_word_keywords', to='blog.magicword', verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بروز کننده'),
        ),
    ]
