# Generated by Django 4.2.6 on 2023-10-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='generated_url_id',
            field=models.CharField(default=1, editable=False, max_length=255, verbose_name='آیدی دامنه سیستمی'),
            preserve_default=False,
        ),
    ]
