# Generated by Django 4.2.6 on 2023-10-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_generated_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='generated_url',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='دامنه سیستمی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='generated_url_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='آیدی دامنه سیستمی'),
        ),
    ]
