# Generated by Django 4.2.6 on 2023-10-31 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_filegallery_alt_alter_filegallery_file'),
        ('blog', '0003_alter_blog_generated_url_alter_blog_generated_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.filegallery', verbose_name='تصویر شاخص'),
        ),
    ]
