# Generated by Django 4.2.2 on 2023-10-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New folder', max_length=255, verbose_name='عنوان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='folder_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.folder', verbose_name='پوشه مادر')),
            ],
            options={
                'verbose_name': '1 - فولدر',
                'verbose_name_plural': '1 - فولدر ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='محتوای سند')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('allowed_to', models.ManyToManyField(blank=True, related_name='document_edit_allowed_to', to=settings.AUTH_USER_MODEL, verbose_name='اجازه دسترسی به')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='document_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده')),
                ('document_parent', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document', verbose_name='پرونده مادر')),
                ('files', models.ManyToManyField(blank=True, to='gallery.filegallery', verbose_name='فایل ها')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.folder', verbose_name='پوشه')),
            ],
            options={
                'verbose_name': '2 - سند',
                'verbose_name_plural': '2 - اسناد',
                'ordering': ['-updated_at'],
            },
        ),
    ]
