# Generated by Django 5.0 on 2024-02-11 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receiver', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Envelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('mailing_history', models.JSONField(blank=True, null=True, verbose_name='تاریخچه ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelop_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('member_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelop_member_from', to=settings.AUTH_USER_MODEL, verbose_name='ارسال شده از')),
                ('member_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelop_member_to', to=settings.AUTH_USER_MODEL, verbose_name='ارسال شده به')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelop_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'نامه',
                'verbose_name_plural': 'نامه ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('همه', 'همه'), ('زیردست', 'زیردست'), ('خود', 'خود')], max_length=255, verbose_name='سطح دسترسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_member_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='عضو')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_member_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'عضو پروژه',
                'verbose_name_plural': 'اعضای پروژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='automation.projectmember', verbose_name='اعضا'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.role', verbose_name='نقش'),
        ),
        migrations.CreateModel(
            name='ProjectInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='وضعیت پذیرش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invite_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.project', verbose_name='پروژه')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invite_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('suggested_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.role', verbose_name='نقش پیشنهادی')),
            ],
            options={
                'verbose_name': 'دعوت به پروژه',
                'verbose_name_plural': 'دعوت های به پروژه',
                'ordering': ['-created_at'],
            },
        ),
    ]
