# Generated by Django 5.0 on 2024-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='access_level',
        ),
        migrations.AddField(
            model_name='role',
            name='access_level',
            field=models.CharField(choices=[('همه', 'همه'), ('زیردست', 'زیردست'), ('خود', 'خود')], default=1, max_length=255, verbose_name='سطح دسترسی'),
            preserve_default=False,
        ),
    ]
