# Generated by Django 5.0 on 2024-02-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to='automation.projectmember', verbose_name='اعضا'),
        ),
    ]
