# Generated by Django 5.0 on 2024-02-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receiver', to='automation.project', verbose_name='گیرنده'),
        ),
    ]
